# Configuration for Readme-Workflows/recent-activity@v2
# Full options: https://github.com/Readme-Workflows/recent-activity/blob/main/docs/Configuration.md

settings:
  username: "krshillman"
  commit_msg: "chore: update recent activity [skip ci]"
  max_lines: 10
  readme_file: "./README.md"
  date:
    timezone: "Australia/Melbourne"
    text: "Last updated: {DATE}"
    format: "dddd, mmmm dS, yyyy, h:MM:ss TT"
